name: Deploy to DigitalOcean (SSH)

on:
  push:
    branches: ["main"]
  # Optional: allow manual runs from the Actions tab
  workflow_dispatch:

concurrency:
  group: deploy-do
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key & known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Default to port 22 if not provided
          PORT="${SSH_PORT:-22}"
          ssh-keyscan -p "$PORT" -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy with rsync (overwrite + delete extraneous files)
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set -euo pipefail
          PORT="${SSH_PORT:-22}"
          rsync -az --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            -e "ssh -p $PORT -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" \
            ./ "$SSH_USER@$SSH_HOST:/var/www/rshelopal.site/"
